#! /bin/bash

#Download CMS Drupal 8
if [ ! -d /var/www/drupal ]
then
	wget -q https://ftp.drupal.org/files/projects/drupal-8.3.3.tar.gz && \
	tar -zxf drupal-8.3.3.tar.gz && \
	mv drupal-8.3.3 /var/www/drupal && \
	rm drupal-8.3.3.tar.gz && \
	chown -R www-data:www-data /var/www/drupal
fi

#Change ip php listener
#ipaddr=$(dig +short phpfpm)
#sed -i "s/FPMADDR/$ipaddr/g" /etc/apache2/sites-available/drupal.conf

#Change port
sed -i "s/80/8080/g" /etc/apache2/ports.conf

#Start apache proccess
killall apache2
apache2ctl -D FOREGROUND

