#! /bin/bash

#Download CMS Drupal 8
wget -q https://ftp.drupal.org/files/projects/drupal-8.3.2.tar.gz && \
tar -zxf drupal-8.3.2.tar.gz && \
mv drupal-8.3.2 /var/www/drupal && \
rm drupal-8.3.2.tar.gz && \
chown -R www-data:www-data /var/www/drupal

#Change ip php listener
ipaddr=$(dig +short phpfpm)
sed -i "s/FPMADDR/$ipaddr/g" /etc/apache2/sites-available/drupal.conf

#Start apache proccess
killall apache2
apache2ctl -D FOREGROUND

