#!/bin/bash
ipaddr=$(dig +short apache)
sed -i "s/APACHEADDR/$ipaddr/g" /etc/varnish/default.vcl
/usr/sbin/varnishd -F -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m


