#! /bin/bash
# Set container IP
CONTAINER_IP=$(ip -o -4 addr show dev eth0 | sed 's/.* inet \([^/]*\).*/\1/')

# PHP5-FPM configuration

sed -i "s/#CONTAINER_IP/$CONTAINER_IP/" /etc/php5/fpm/pool.d/www.conf
killall php7.0-fpm
mkdir -p /var/www
php7.0-fpm

