#! /bin/bash
# Set container IP
CONTAINER_IP=$(ip -o -4 addr show dev eth0 | sed 's/.* inet \([^/]*\).*/\1/')

# PHP7.0-FPM configuration
sed -i "s/#CONTAINER_IP/$CONTAINER_IP/" /etc/php7.0/fpm/pool.d/www.conf
killall php-fpm7.0
mkdir -p /var/www
php-fpm7.0

#Download drupal
wget https://ftp.drupal.org/files/projects/drupal-8.3.2.tar.gz -q
tar -zxf drupal-8.3.2.tar.gz
mv drupal-8.3.2 /var/www/drupal
rm drupal-8.3.2.tar.gz -f
